#Headless browser option
browser:
 #  webkit: "phantomjs"
   gecko: "slimerjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "javascript/snap.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'shots'

# Add only 2 domains, key will act as a label
domains:
#  english: "http://www.live.bbc.co.uk/news"
#  russian: "http://www.live.bbc.co.uk/russian"
  one: "http://www.vw.com"
  two: "http://www.vw.com"
#  spanish: "http://www.vw.com"
#  vwcars: "http://www.vw.com/models"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 600
  - 768
  - 1024
  - 1280
#  - 1920

#Type page URL paths below, here are a couple of examples
#paths:
#  before: /
#  uk_index: /uk

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

paths:
 - /
 - /models/
 - /models/golf/
 - /models/gti/
 - /models/beetle/
 - /models/beetle-convertible/
 - /models/eos/
 - /models/jetta/
 - /models/cc/
 - /models/passat/
 - /models/jetta-sportwagen/
 - /models/tiguan/
 - /models/touareg/
 - /features/
 - /features/clean-diesel/
 - /features/hybrid/
 - /features/premium-audio/
 - /features/panoramic-sunroof/
 - /features/vw-car-net/
 - /features/performance/
 - /terms/
 - /privacy/
 - /find-match/
 - /find-match/models/
 - /find-match/engine/
 - /find-match/colors/
 - /find-match/features/
 - /find-match/budget/
 - /find-match/new-cars/
 - /find-match/used-cars/
 - /find-a-dealer/
 - /profile/
 - /special-offers/
 - /financial-services/
 - /financial-services/vehicle-protection/
 - /financial-services/ownership-experience/
 - /financial-services/glossary/
 - /financial-services/contact-us/
 - /financial-services/lease-a-vehicle/
 - /financial-services/finance-a-vehicle/
 - /owners/
 - /web/vw/recall/index.html/
 - /certified-pre-owned/
 - /social-news/
 - /corporate/
 - /contact/
 - /faq/
 - /vw-sponsorship/
 - /site-map/

#Amount of fuzz ImageMagick will use
fuzz: '20%'

#Set the spider
#Is this needed?
#spider: spider/test.txt

#Set the number of days to keep the site spider file
spider_days:
  - 10
